all:	HW04

HW04:
		
		g++ -std=c++0x	-c fatih_oguz_151044025.cpp
		g++ -std=c++0x	-c read.cpp
		g++ -std=c++0x 	-c lecturer.cpp
		g++ -std=c++0x 	-c administrator.cpp
		g++ -std=c++0x 	-c test.cpp
		g++ -std=c++0x 	-c student.cpp
		g++ -std=c++0x 	-c classroom.cpp
		g++ -o HW04 fatih_oguz_151044025.o lecturer.o read.o administrator.o test.o student.o classroom.o
		./HW04 
clean:
		rm *.o HW04

