all:	HW03

HW03:
		
		g++ -std=c++0x	-c fatih_oguz_151044025.cpp
		g++ -std=c++0x	-c read.cpp
		g++ -std=c++0x 	-c lecturer.cpp
		g++ -std=c++0x 	-c administrator.cpp
		g++ -std=c++0x 	-c test.cpp
		g++ -o HW03 fatih_oguz_151044025.o lecturer.o read.o administrator.o test.o
		./HW03 
clean:
		rm *.o HW03

